// packages/angular/src/createProgrammable.ts
import {
  Component,
  ElementRef,
  inject,
  Input,
  ViewChild,
  ViewContainerRef,
  type AfterViewInit,
  type ComponentRef,
  type OnDestroy,
  type OnInit,
  type Type,
} from "@angular/core";
import * as AngularCommon from "@angular/common";
import * as AngularCore from "@angular/core";
import { createWishkit, type ProgrammableOptions, type Wishkit } from "@wishkit/dom";
import wasmURL from "esbuild-wasm/esbuild.wasm?url";
import { createAngularCompiler } from "./compiler";
import { angular } from "./framework";

export type { ProgrammableOptions };

/** What createProgrammable() returns: pass it to <wish-root> and <wish-panel>. */
export type Programmable = Wishkit;

/**
 * Makes the folder in `options.files` programmable. Render it with
 * `<wish-root [wish]="wish" />` and add the panel with `<wish-panel [wish]="wish" />`.
 */
export function createProgrammable(options: ProgrammableOptions): Programmable {
  return createWishkit(options, {
    framework: angular,
    entry: "index.ts",
    packages: { "@angular/core": AngularCore, "@angular/common": AngularCommon },
    compiler: createAngularCompiler({ wasmURL }),
  });
}

/**
 * Renders the programmable entry and swaps in the user's latest version live. A version that
 * throws on its first render is replaced by a message and reported, so the runtime rolls back.
 */
@Component({
  selector: "wish-root",
  template: "<ng-container #outlet />",
  // The same attribute as ROOT_ATTRIBUTE, written out so the metadata stays static.
  host: { "data-wish-root": "", style: "display: contents" },
})
export class WishRoot implements OnInit, OnDestroy {
  @Input({ required: true }) wish!: Programmable;
  @ViewChild("outlet", { read: ViewContainerRef, static: true }) private outlet!: ViewContainerRef;
  private readonly host: HTMLElement = inject(ElementRef).nativeElement;
  private shown?: ComponentRef<unknown>;
  private alert?: HTMLElement;
  private unsubscribe?: () => void;

  ngOnInit() {
    this.show();
    this.unsubscribe = this.wish.runtime.subscribe(() => this.show());
    // Brings back the user's saved wishes once something is mounted to render them.
    void this.wish.wishes.ready();
  }

  ngOnDestroy() {
    this.unsubscribe?.();
  }

  private show() {
    const { runtime } = this.wish;
    const { entry, version } = runtime.getSnapshot();
    this.outlet.clear();
    this.alert?.remove();
    try {
      this.shown = this.outlet.createComponent(entry as Type<unknown>);
      this.shown.changeDetectorRef.detectChanges();
      runtime.reportRender(version);
    } catch (caught) {
      const error = caught instanceof Error ? caught : new Error(String(caught));
      this.outlet.clear();
      this.alert = this.host.ownerDocument.createElement("div");
      this.alert.setAttribute("role", "alert");
      this.alert.textContent = `This part of the app failed to render: ${error.message}`;
      this.host.append(this.alert);
      runtime.reportRender(version, error);
    }
  }
}

/** The floating panel where users select part of the app and make wishes. */
@Component({ selector: "wish-panel", template: "", host: { style: "display: contents" } })
export class WishPanel implements AfterViewInit, OnDestroy {
  @Input({ required: true }) wish!: Programmable;
  private readonly host: HTMLElement = inject(ElementRef).nativeElement;
  private unmount?: () => void;

  ngAfterViewInit() {
    this.unmount = this.wish.mountPanel(this.host);
  }

  ngOnDestroy() {
    this.unmount?.();
  }
}

// packages/react/src/createProgrammable.tsx
import {
  createEsbuildCompiler,
  createProgrammableRuntime,
  createWishList,
  type Compiler,
  type ProgrammableFiles,
  type ProgrammableRuntime,
  type Wisher,
  type WishStore,
} from "@wishkit/core";
import wasmURL from "esbuild-wasm/esbuild.wasm?url";
import * as React from "react";
import { Component, useEffect, useSyncExternalStore, type ComponentType, type ReactNode } from "react";
import * as jsxRuntime from "react/jsx-runtime";
import type { ApiKeyStore } from "./apiKey";
import { Panel as WishPanel } from "./Panel";
import { localWishStore } from "./wishStore";

export type ProgrammableOptions = {
  /** The programmable folder, usually `import files from "virtual:wishkit/programmable"`. */
  files: ProgrammableFiles;
  /** The file whose default export `<Root />` renders. Defaults to "index.tsx". */
  entry?: string;
  /** Files wishes may import but never change. Defaults to ["capabilities.ts"]. */
  locked?: string[];
  /** Extra packages programmable code may import, by specifier. React is always included. */
  packages?: Record<string, unknown>;
  compiler?: Compiler;
  /** Turns wishes into changes, e.g. createClaudeWisher() from @wishkit/llm. */
  wisher?: Wisher;
  /** When given, the panel asks the user for an API key and keeps it here. */
  apiKey?: ApiKeyStore;
  /** Where the user's wishes are kept. Defaults to this browser's localStorage. */
  store?: WishStore;
};

type BoundaryProps = { children: ReactNode; onError?: (error: Error) => void };

class RenderBoundary extends Component<BoundaryProps, { error: Error | null }> {
  state = { error: null as Error | null };

  static getDerivedStateFromError(error: Error) {
    return { error };
  }

  componentDidCatch(error: Error) {
    this.props.onError?.(error);
  }

  render() {
    if (this.state.error) {
      return <div role="alert">This part of the app failed to render: {this.state.error.message}</div>;
    }
    return this.props.children;
  }
}

export function createProgrammable(options: ProgrammableOptions) {
  const runtime: ProgrammableRuntime = createProgrammableRuntime({
    files: options.files,
    entry: options.entry ?? "index.tsx",
    locked: options.locked ?? ["capabilities.ts"],
    packages: { react: React, "react/jsx-runtime": jsxRuntime, ...options.packages },
    compiler: options.compiler ?? createEsbuildCompiler({ wasmURL }),
  });

  const wishes = createWishList({
    store: options.store ?? localWishStore(),
    sources: options.files.sources,
    apply: (overlay) => runtime.tryApply(overlay),
    current: () => runtime.getSnapshot().overlay,
  });

  /** Tells the runtime a version rendered, so tryApply() can keep it. */
  function Rendered({ version }: { version: number }) {
    useEffect(() => runtime.reportRender(version), [version]);
    return null;
  }

  /** Renders the programmable entry, swapping in the user's latest version live. Props pass through. */
  function Root(props: Record<string, unknown>) {
    const snapshot = useSyncExternalStore(runtime.subscribe, runtime.getSnapshot);
    const Entry = snapshot.entry as ComponentType<Record<string, unknown>>;
    // Brings back the user's saved wishes once something is mounted to render them.
    useEffect(() => {
      void wishes.ready();
    }, []);
    return (
      <div data-wish-root="" style={{ display: "contents" }}>
        <RenderBoundary key={snapshot.version} onError={(error) => runtime.reportRender(snapshot.version, error)}>
          <Entry {...props} />
          <Rendered version={snapshot.version} />
        </RenderBoundary>
      </div>
    );
  }

  /** The floating panel where users select part of the app and make wishes. */
  function Panel() {
    return <WishPanel runtime={runtime} wishes={wishes} wisher={options.wisher} apiKey={options.apiKey} />;
  }

  return { runtime, wishes, Root, Panel };
}
