// examples/vue-tasks/src/programmable/TaskList.vue
<script setup lang="ts">
import { ref } from "vue";
import { tasks } from "./capabilities";

const title = ref("");

function onSubmit() {
  tasks.add(title.value);
  title.value = "";
}
</script>

<template>
  <section class="task-list">
    <h2>Tasks</h2>
    <ul>
      <li v-for="task in tasks.all.value" :key="task.id" :class="{ done: task.done }">
        <label>
          <input type="checkbox" :checked="task.done" @change="tasks.toggle(task.id)" />
          <span>{{ task.title }}</span>
        </label>
        <button type="button" :aria-label="`Delete ${task.title}`" @click="tasks.remove(task.id)">×</button>
      </li>
    </ul>
    <form @submit.prevent="onSubmit">
      <input v-model="title" aria-label="New task" placeholder="Add a task" />
      <button type="submit">Add</button>
    </form>
  </section>
</template>

// examples/web-tasks/src/programmable/TaskList.tsx
import { useState, type FormEvent } from "react";
import { tasks } from "./capabilities";

export function TaskList() {
  const all = tasks.useAll();
  const [title, setTitle] = useState("");

  function onSubmit(event: FormEvent) {
    event.preventDefault();
    tasks.add(title);
    setTitle("");
  }

  return (
    <section className="task-list">
      <h2>Tasks</h2>
      <ul>
        {all.map((task) => (
          <li key={task.id} className={task.done ? "done" : undefined}>
            <label>
              <input type="checkbox" checked={task.done} onChange={() => tasks.toggle(task.id)} />
              <span>{task.title}</span>
            </label>
            <button type="button" aria-label={`Delete ${task.title}`} onClick={() => tasks.remove(task.id)}>
              ×
            </button>
          </li>
        ))}
      </ul>
      <form onSubmit={onSubmit}>
        <input
          aria-label="New task"
          placeholder="Add a task"
          value={title}
          onChange={(event) => setTitle(event.target.value)}
        />
        <button type="submit">Add</button>
      </form>
    </section>
  );
}
